openapi: 3.0.1
info:
  title: Fibonnacci.Api
  version: '1.0'
paths:
  '/api/fibonacci/{len}':
    get:
      tags:
        - Fibonnacci.Api
      operationId: Get Fibonacci sequence
      parameters:
        - name: len
          in: path
          required: true
          style: simple
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  type: integer
                  format: int32
components: { }