openapi: 3.0.1
info:
  title: StarWars.Api
  version: '1.0'
servers:
  - url: https://apim-dev-dthsylghbqchu.azure-api.net/sw
paths:
  /api/all:
    get:
      tags:
        - StarWars.Api
      summary: GetAllCharacters
      description: GetAllCharacters
      operationId: GetAllCharacters
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CharactersDTO'
              example:
                - id: 0
                  name: string
                  planet: string
                  affiliation: string
components:
  schemas:
    CharactersDTO:
      type: object
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
          nullable: true
        planet:
          type: string
          nullable: true
        affiliation:
          type: string
          nullable: true
      additionalProperties: false
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]