name: Deploy Star Wars Api

on:
  workflow_dispatch:
    
jobs:
  deploy-in-dev-environment:
    uses: ./.github/workflows/deployWebapp.yml
    with:        
      environment: 'dev'
      azure_web_app_package: src/StarWars.Api
    secrets:
      webappname: ${{ secrets.WEBAPP_SW_DEV_NAME }} 
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }} 

  deploy-in-prod-environment:
    needs: deploy-in-dev-environment
    uses: ./.github/workflows/deployWebapp.yml
    with:        
      environment: 'prod'
      azure_web_app_package: src/StarWars.Api
    secrets:
      webappname: ${{ secrets.WEBAPP_SW_PROD_NAME }} 
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}       