name: Configure Application Gateway

on:
  workflow_dispatch:    

jobs:
  deploy-configure-app-gateway:

    runs-on: ubuntu-latest

    steps:
      
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: azure/arm-deploy@v1
        id: deployGateway
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: ${{ secrets.SPOKE_RESOURCE_GROUP_NAME }}
          deploymentName:  ${{ github.run_id }}
          template: ./infra/opsTeam/gateway.bicep        
          parameters: gwSubnetId=${{ secrets.SUBNET_GATEWAY_ID }} certLink=${{ secrets.SECRET_CERT_LINK }} apiGwHostname=${{ secrets.API_HOSTNAME }} devPortalFqdn=${{ secrets.DEV_PORTAL_HOSTAME }} managementFqdn=${{ secrets.MANAGEMENT_HOSTNAME }} location=${{ secrets.LOCATION}} identityId=${{ secrets.USER_IDENTITY_ID }}