name: Create Azure Resources

on:
  push:
    branches:
      - main
    paths:
      - 'infra/**.bicep'
      - '.github/workflows/createAzureResources.yml'

  workflow_dispatch:    

jobs:
  create-azure-resources:

    runs-on: ubuntu-latest

    steps:
      
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: deploy
        id: createResources
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          scope: subscription
          region: ${{ secrets.LOCATION }}
          deploymentName:  ${{ github.run_id }}
          template: ./infra/opsTeam/main.bicep
          parameters: location=${{ secrets.LOCATION }} publisherName=${{ secrets.PUBLISHER_NAME }} publisherEmail=${{ secrets.PUBLISHER_EMAIL }} dnsZoneName=${{ secrets.CUSTOM_DOMAIN_NAME }}
            
