name: Fix missing secrets

on:
  workflow_dispatch:    

jobs:
  deploy-configure-app-gateway:

    runs-on: ubuntu-latest

    steps:
      
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: azure/arm-deploy@v1
        id: fix
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: ${{ secrets.SPOKE_RESOURCE_GROUP_NAME }}
          deploymentName:  ${{ github.run_id }}
          template: ./infra/opsTeam/temp.bicep       
          
      - uses: gliech/create-github-secret-action@v1
        with:
          name: SUBNET_GATEWAY_ID
          value: ${{ steps.fix.outputs.subnetIdOne }}
          pa_token: ${{ secrets.PA_TOKEN }}            